### ISSUE TITLE
[FEAT] 모달에서 사용하는 데이터를 front에서 요청하고 받아올수 있도록 구현

### ISSUE THREAD

**Issue by moonyoungCHAE** [woowacourse-teams/2020-songpa-people#16]
기능 구현 대상 : 
req
* 가게 id

res
* 가게 이름
* 해시태그 개수
* 인스타그램 정보
  * (검색 결과에 해당하는) 인스타그램 url ('리얼파스타'를 검색한 instagram url)
  * 인스타그램 포스팅 이미지 url 
  * 인스타그램 포스팅 url (redirect 할 url)
* 카카오 url (가게에 해당하는 상세 페이지)

예상 공수 기간 : 

특이 사항(optional) :
* 모달 View연결까지 하기

**Comment by DunDung** [comment]
완료.
