### ISSUE TITLE
[FEAT] Index Page 한 번만 나오게 하기

### ISSUE THREAD

**Issue by moonyoungCHAE** [woowacourse-teams/2020-songpa-people#187]
기능 구현 대상 : 
* 사용자에게 Index Page를 한 번만 보여준다.
* 한 번 들어온 사용자는 다시 접속했을 때 Index Page를 보지 않는다.

예상 공수 기간 : 

특이 사항(optional) :
* 쿠키로 한다

**Comment by pci2676** [comment]
그런데 다시 index page로 돌아갈수는 있게 만들어야 하지 않을까요?

**Comment by moonyoungCHAE** [comment]
맞네요 ... 그러면 로고 누르면 index 가거나 해야겠네요
잊어버릴까봐 이슈 등록했는데 중요한 건 아니니 나중에 정해봅시다~
