### ISSUE TITLE
[BUG] Safari 에서 모바일 메뉴 깨지는 부분

### ISSUE THREAD

**Issue by pci2676** [woowacourse-teams/2020-songpa-people#209]
버그 발견 일자 : 2020.08.26

버그 내용 및 위치 : web-front

![image](https://user-images.githubusercontent.com/13347548/91300260-f1476c80-e7dd-11ea-8abf-c95209e13a5c.png)

버그 중요도 : 상

특이 사항(optional) :

빠른 수정...!!

**Comment by giantim** [comment]
확인 결과 사파리 모바일 버전, 웹 버전 모두 css가 깨지고 있습니다~

**Comment by giantim** [comment]
[여기 보고 수정했습니다.](https://github.com/vuetifyjs/vuetify/issues/5351)
