### ISSUE TITLE
[REFACTOR] Instagram 스케줄러 모듈 네이밍 및 구조 수정

### ISSUE THREAD

**Issue by moonyoungCHAE** [woowacourse-teams/2020-songpa-people#258]
리팩토링 대상 : 

예상 공수 기간 : 

특이 사항(optional) :

**Comment by giantim** [comment]
모듈 이름: hashtagmap-instagram-scheduler -> hashtagmap-instagram-service
클래스 이름:
InstagramSchedulerConfiguration -> InstagramServiceConfiguration
InstagramSchedulerException -> InstagramServiceException
InstagramSchedulerExceptionStatus -> InstagramServiceExceptionStatus
InstagramScheduler -> InstagramService
InstagramScheduleService -> InstagramCrawlingService

어떻게 생각하시나요?
적절한 이름을 생각하다 보니까 instagram-scheduler 모듈과 instagram-crawler 모듈을 합치는 리팩토링이 필요해 보이기는 합니다....

**Comment by giantim** [comment]
#275 
머지 되었으므로 이슈 닫겠습니다.
