### ISSUE TITLE
[DOCS] 구글 지도 API 분석

### ISSUE THREAD

**Issue by DunDung** [woowacourse-teams/2020-songpa-people#3]
기능 구현 대상 : 지도 API 분석 (데이터 수집을 어떻게 할지에 대한)
* 기능
* 요청
* 응답

(예시) 
![image](https://user-images.githubusercontent.com/37133536/86100484-d44f2f80-baf3-11ea-8579-e284b72f198a.png)

예상 공수 기간 : ~ 7.9

특이 사항(optional) :

**Comment by moonyoungCHAE** [comment]
카카오가 너무 완벽해서 넘어가기로 함
