### ISSUE TITLE
[FEAT] 예외 처리 팀 컨벤션 정하기

### ISSUE THREAD

**Issue by giantim** [woowacourse-teams/2020-songpa-people#44]
기능 구현 대상 : 
각 모듈에서 발생한 예외에 대해 처리하는 방법을 구체적으로 정한다.

예상 공수 기간 : 

특이 사항(optional) :

**Comment by moonyoungCHAE** [comment]
[회의](https://github.com/woowacourse-teams/2020-songpa-people/wiki/Custom-Exception-(20.07.24))
